# File: environment.yml
name: whisper
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  - pip

  # ML/Audio Processing
  - pytorch>=2.5.1  # Will automatically use MPS backend
  - torchaudio>=2.5.1
  - numpy>=2.2.0
  - transformers>=4.37.0  # Added for new Whisper implementation
  - optimum>=1.16.0  # Added for optimized inference
  - accelerate>=0.27.0  # Added for optimized inference

  # Configuration & System
  - pyyaml>=6.0
  - psutil>=5.9.5

  # Progress & UI
  - rich>=13.7.0  # Added for progress reporting
  - tqdm>=4.66.1  # Added for progress bars

  # Testing
  - pytest>=7.5.0

  # Text Processing
  - rapidfuzz>=3.2.0
  - jellyfish>=0.11.0

  # Audio Input
  - portaudio  # Required for PyAudio

  # Web Framework
  - fastapi>=0.110.3
  - uvicorn>=0.27.4
  - pydantic>=2.4.0
  - python-multipart>=0.0.6
  - aiofiles>=23.2.1
  - jinja2>=3.1.2

  # Development Tools
  - ruff=0.3.0
  - mypy=1.14.1
  - pre-commit>=4.0.1
  - coverage>=7.4.2
  - pytest-cov>=4.1.0

  # Type Stubs
  - types-PyYAML>=6.0
  - types-setuptools>=68.0.0
  - types-requests>=2.31.0
  - types-psutil>=5.9.0

  # Pip-specific packages
  - pip:
    - openai-whisper
    - soundfile>=0.13.0
    - PyAudio>=0.2.14
    - pytorch-lightning>=2.5.0
    - pyannote.audio>=3.1.1
    - pytest-assume>=2.4.3
    - pytest-asyncio>=0.23.5
    - httpx>=0.27.0
    - scipy
    - insanely-fast-whisper>=0.0.15  # Added for optimized Whisper
