# File: environment.yml
name: whisper
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12  # Updated from 3.10
  - pip

  # ML/Audio Processing
  - pytorch>=2.1.0
  - torchaudio>=2.1.0
  - numpy>=1.26.0
  - scipy>=1.11.3

  # Configuration & System
  - pyyaml>=6.0
  - psutil>=5.9.5

  # Testing
  - pytest>=7.5.0

  # Text Processing
  - rapidfuzz>=3.2.0
  - jellyfish>=0.11.0

  # Audio Input
  - portaudio  # Required for PyAudio

  # Web Framework
  - fastapi>=0.110.3
  - uvicorn>=0.27.4
  - pydantic>=2.4.0
  - python-multipart>=0.0.6  # For handling file uploads
  - aiofiles>=23.2.1  # For async file operations
  - jinja2>=3.1.2  # For template rendering

  # Development Tools
  - ruff=0.3.0  # Pin exact version
  - mypy=1.14.1  # Pin exact version
  - pre-commit>=4.0.1
  - coverage>=7.4.2
  - pytest-cov>=4.1.0  # Add pytest coverage plugin

  # Type Stubs
  - types-PyYAML>=6.0
  - types-setuptools>=68.0.0
  - types-requests>=2.31.0
  - types-psutil>=5.9.0

  # Pip-specific packages
  - pip:
    - openai-whisper>=20240930
    - soundfile>=0.13.0
    - PyAudio>=0.2.14
    - pytorch-lightning>=2.5.0
    - pyannote.audio>=3.1
    - pytest-assume>=2.4.3  # For multiple assertions per test
